export interface StoryLinkType {
  label: string;
  color: string;
  dashed?: boolean;
}

export const STORY_LINK_TYPES: Record<string, StoryLinkType> = {
  'home of': { label: 'Home of', color: '#c8a876' },
  'lives in': { label: 'Lives in', color: '#38bdf8' },
  'part of': { label: 'Part of', color: '#7f8fa3' },
  'located in': { label: 'Located in', color: '#34d399' },
  'portal to': { label: 'Portal to', color: '#a78bfa' },
  guards: { label: 'Guards', color: '#4ade80' },
  protects: { label: 'Protects', color: '#4ade80' },
  rules: { label: 'Rules', color: '#fbbf24' },
  'rank of': { label: 'Rank of', color: '#facc15' },
  serves: { label: 'Serves', color: '#c084fc' },
  chooses: { label: 'Chooses', color: '#fbbf24' },
  uses: { label: 'Uses', color: '#2dd4bf' },
  'corrupted from': { label: 'Corrupted from', color: '#a855f7' },
  causes: { label: 'Causes', color: '#f87171' },
  'fused from': { label: 'Fused from', color: '#e879f9' },
  studies: { label: 'Studies', color: '#4ade80' },
  kills: { label: 'Can kill', color: '#f87171' },
  'sealed in': { label: 'Sealed in', color: '#38bdf8' },
  'lost in': { label: 'Lost in', color: '#7f8fa3', dashed: true },
  'found in': { label: 'Found in', color: '#f97316' },
  'crafted by': { label: 'Crafted by', color: '#f472b6' },
  seals: { label: 'Seals', color: '#fb923c' },
  produces: { label: 'Produces', color: '#c084fc' },
  'made from': { label: 'Made from', color: '#facc15' },
  'refined from': { label: 'Refined from', color: '#38bdf8' },
  'ingredient of': { label: 'Ingredient of', color: '#4ade80' },
  'needed for': { label: 'Needed for', color: '#fb923c' },
  'story of': { label: 'Story of', color: '#c084fc' },
  'innate of': { label: 'Innate of', color: '#2dd4bf' },
  about: { label: 'About', color: '#7f8fa3' },
  'hungers like': { label: 'Hungers like', color: '#fbbf24' },
  'given to': { label: 'Given to', color: '#fb923c' },
  'found by': { label: 'Found by', color: '#34d399' },
  'passed down': { label: 'Passed down', color: '#818cf8' },
  'owned by': { label: 'Owned by', color: '#f472b6' },
  'skill of': { label: 'Skill of', color: '#4ade80' },
  'form of': { label: 'Form of', color: '#f472b6' },
  'class of': { label: 'Class of', color: '#38bdf8' },
  'progresses to': { label: 'Progresses to', color: '#818cf8' },
  'Leader of': { label: 'Leader of', color: '#fbbf24' },
  About: { label: 'About', color: '#7f8fa3' },
  "Can't": { label: "Can't", color: '#f87171' },
  'Evolve to': { label: 'Evolve to', color: '#818cf8' },
  'Goes to': { label: 'Goes to', color: '#38bdf8' },
  Joined: { label: 'Joined', color: '#4ade80' },
  'Sold by': { label: 'Sold by', color: '#f472b6' },
  'Teacher at': { label: 'Teacher at', color: '#2dd4bf' },
  'Used by': { label: 'Used by', color: '#2dd4bf' },
  'head master of': { label: 'Head Master of', color: '#facc15' },
  'held by': { label: 'Held by', color: '#fbbf24' },
  'hides in': { label: 'Hides in', color: '#7f8fa3' },
  'cursed by': { label: 'Cursed by', color: '#a855f7' },
  // Six Pillars / Six Fingers
  defend: { label: 'Defend', color: '#f87171' },
  serve: { label: 'Serve', color: '#c084fc' },
  'First Finger is': { label: 'First Finger is', color: '#a855f7' },
  'Second Finger was': { label: 'Second Finger was', color: '#a855f7' },
  'Third Finger is': { label: 'Third Finger is', color: '#a855f7' },
  'Fourth Finger is': { label: 'Fourth Finger is', color: '#a855f7' },
  'Fifth Finger is': { label: 'Fifth Finger is', color: '#a855f7' },
  'Sixth Finger is': { label: 'Sixth Finger is', color: '#a855f7' },
  'First Pillar is': { label: 'First Pillar is', color: '#fbbf24' },
  'Second Pillar is': { label: 'Second Pillar is', color: '#fbbf24' },
  'Third Pillar is': { label: 'Third Pillar is', color: '#fbbf24' },
  'Fourth Pillar is': { label: 'Fourth Pillar is', color: '#fbbf24' },
  'Fifth Pillar is': { label: 'Fifth Pillar is', color: '#fbbf24' },
  'Sixth Pillar is': { label: 'Sixth Pillar is', color: '#fbbf24' },
  'was First Pillar of': { label: 'Was First Pillar of', color: '#fbbf24' },
  'was Second Pillar of': { label: 'Was Second Pillar of', color: '#fbbf24' },
  includes: { label: 'Includes', color: '#34d399' },
  'guardian of': { label: 'Guardian of', color: '#4ade80' },
  'holds title': { label: 'Holds title', color: '#fbbf24' },
  'is': { label: 'Is', color: '#7f8fa3' },
  'achieved by': { label: 'Achieved By', color: '#c8a876' },
  'advancement method of': { label: 'Advancement Method Of', color: '#f87171' },
  'advances from': { label: 'Advances From', color: '#a855f7' },
  'advances to': { label: 'Advances To', color: '#fde047' },
  'affects': { label: 'Affects', color: '#fde047' },
  'alternative to': { label: 'Alternative To', color: '#fda4af' },
  'antagonist in': { label: 'Antagonist In', color: '#818cf8' },
  'applies to': { label: 'Applies To', color: '#a855f7' },
  'approached via': { label: 'Approached Via', color: '#fbbf24' },
  'barrier within': { label: 'Barrier Within', color: '#5eead4' },
  'belongs to': { label: 'Belongs To', color: '#c4b5fd' },
  'blessed': { label: 'Blessed', color: '#facc15' },
  'blocks': { label: 'Blocks', color: '#e879f9' },
  'bonded to': { label: 'Bonded To', color: '#a855f7' },
  'born from': { label: 'Born From', color: '#c4b5fd' },
  'born in': { label: 'Born In', color: '#c8a876' },
  'branches from': { label: 'Branches From', color: '#fda4af' },
  'breach triggers': { label: 'Breach Triggers', color: '#f87171' },
  'built by': { label: 'Built By', color: '#a855f7' },
  'built using knowledge of': { label: 'Built Using Knowledge Of', color: '#bef264' },
  'calms': { label: 'Calms', color: '#4ade80' },
  'can be harmed by': { label: 'Can Be Harmed By', color: '#fb7185' },
  'can develop': { label: 'Can Develop', color: '#bef264' },
  'can use': { label: 'Can Use', color: '#fb7185' },
  'capital of': { label: 'Capital Of', color: '#a78bfa' },
  'caused': { label: 'Caused', color: '#bef264' },
  'caused by': { label: 'Caused By', color: '#5eead4' },
  'channels': { label: 'Channels', color: '#f472b6' },
  'child of': { label: 'Child Of', color: '#818cf8' },
  'circulates in': { label: 'Circulates In', color: '#fde047' },
  'coexist with': { label: 'Coexist With', color: '#a855f7' },
  'compared to': { label: 'Compared To', color: '#f87171' },
  'complementary to': { label: 'Complementary To', color: '#38bdf8' },
  'component for': { label: 'Component For', color: '#f472b6' },
  'composed of': { label: 'Composed Of', color: '#a78bfa' },
  'condition of': { label: 'Condition Of', color: '#f472b6' },
  'conducted at': { label: 'Conducted At', color: '#c8a876' },
  'connect to': { label: 'Connect To', color: '#bef264' },
  'connected through': { label: 'Connected Through', color: '#f472b6' },
  'connected to': { label: 'Connected To', color: '#e879f9' },
  'consequence of': { label: 'Consequence Of', color: '#e879f9' },
  'contains': { label: 'Contains', color: '#fb7185' },
  'controlled by': { label: 'Controlled By', color: '#fb923c' },
  'converts from': { label: 'Converts From', color: '#34d399' },
  'converts to': { label: 'Converts To', color: '#fb923c' },
  'corrupted in': { label: 'Corrupted In', color: '#fbbf24' },
  'counters': { label: 'Counters', color: '#c084fc' },
  'crafted at': { label: 'Crafted At', color: '#2dd4bf' },
  'created': { label: 'Created', color: '#c8a876' },
  'created via': { label: 'Created Via', color: '#fda4af' },
  'creates': { label: 'Creates', color: '#a855f7' },
  'cultural bond with': { label: 'Cultural Bond With', color: '#fbbf24' },
  'damaged in': { label: 'Damaged In', color: '#fda4af' },
  'delivered by': { label: 'Delivered By', color: '#fb7185' },
  'describes': { label: 'Describes', color: '#34d399' },
  'describes for': { label: 'Describes For', color: '#c084fc' },
  'details': { label: 'Details', color: '#facc15' },
  'details for': { label: 'Details For', color: '#fb923c' },
  'details of': { label: 'Details Of', color: '#c084fc' },
  'detected by': { label: 'Detected By', color: '#38bdf8' },
  'detected signs of': { label: 'Detected Signs Of', color: '#38bdf8' },
  'determines': { label: 'Determines', color: '#fda4af' },
  'determines starting': { label: 'Determines Starting', color: '#e879f9' },
  'did not trigger': { label: 'Did Not Trigger', color: '#fde047' },
  'discovered by': { label: 'Discovered By', color: '#c084fc' },
  'distinct from': { label: 'Distinct From', color: '#c8a876' },
  'documents': { label: 'Documents', color: '#fda4af' },
  'dwells in': { label: 'Dwells In', color: '#34d399' },
  'enables': { label: 'Enables', color: '#34d399' },
  'evolves from': { label: 'Evolves From', color: '#c8a876' },
  'evolves to': { label: 'Evolves To', color: '#bef264' },
  'example of': { label: 'Example Of', color: '#fb7185' },
  'exception to': { label: 'Exception To', color: '#facc15' },
  'expands on': { label: 'Expands On', color: '#f472b6' },
  'explains': { label: 'Explains', color: '#f472b6' },
  'explains for': { label: 'Explains For', color: '#c084fc' },
  'explains process of': { label: 'Explains Process Of', color: '#34d399' },
  'extensions of': { label: 'Extensions Of', color: '#bef264' },
  'feeds on': { label: 'Feeds On', color: '#2dd4bf' },
  'final stage of': { label: 'Final Stage Of', color: '#bef264' },
  'first stage of': { label: 'First Stage Of', color: '#38bdf8' },
  'fled from': { label: 'Fled From', color: '#c084fc' },
  'flexible for': { label: 'Flexible For', color: '#2dd4bf' },
  'followed by': { label: 'Followed By', color: '#fbbf24' },
  'foretells': { label: 'Foretells', color: '#e879f9' },
  'formed from': { label: 'Formed From', color: '#818cf8' },
  'found at': { label: 'Found At', color: '#818cf8' },
  'found near': { label: 'Found Near', color: '#2dd4bf' },
  'founded': { label: 'Founded', color: '#818cf8' },
  'founded by': { label: 'Founded By', color: '#2dd4bf' },
  'fuels': { label: 'Fuels', color: '#fb923c' },
  'governed by': { label: 'Governed By', color: '#7f8fa3' },
  'governs': { label: 'Governs', color: '#fda4af' },
  'granted by': { label: 'Granted By', color: '#5eead4' },
  'grows in': { label: 'Grows In', color: '#38bdf8' },
  'guarded by': { label: 'Guarded By', color: '#fb7185' },
  'harvested by': { label: 'Harvested By', color: '#fb923c' },
  'has skill': { label: 'Has Skill', color: '#38bdf8' },
  'how formed': { label: 'How Formed', color: '#7f8fa3' },
  'inhabit': { label: 'Inhabit', color: '#fb7185' },
  'inhabited by': { label: 'Inhabited By', color: '#c084fc' },
  'inherits': { label: 'Inherits', color: '#2dd4bf' },
  'initiated by': { label: 'Initiated By', color: '#2dd4bf' },
  'insurance of': { label: 'Insurance Of', color: '#a855f7' },
  'involved in': { label: 'Involved In', color: '#5eead4' },
  'involves': { label: 'Involves', color: '#f87171' },
  'is class': { label: 'Is Class', color: '#4ade80' },
  'leads': { label: 'Leads', color: '#818cf8' },
  'led by': { label: 'Led By', color: '#5eead4' },
  'lesser than': { label: 'Lesser Than', color: '#fbbf24' },
  'located at': { label: 'Located At', color: '#fbbf24' },
  'maintained by': { label: 'Maintained By', color: '#bef264' },
  'managed by': { label: 'Managed By', color: '#2dd4bf' },
  'manages': { label: 'Manages', color: '#fde047' },
  'maps': { label: 'Maps', color: '#38bdf8' },
  'member of': { label: 'Member Of', color: '#fb7185' },
  'mirrors': { label: 'Mirrors', color: '#4ade80' },
  'most famous site of': { label: 'Most Famous Site Of', color: '#4ade80' },
  'native to': { label: 'Native To', color: '#f87171' },
  'occasionally hosts': { label: 'Occasionally Hosts', color: '#facc15' },
  'occurs at': { label: 'Occurs At', color: '#34d399' },
  'occurs in': { label: 'Occurs In', color: '#34d399' },
  'one located at': { label: 'One Located At', color: '#fbbf24' },
  'only brewer of': { label: 'Only Brewer Of', color: '#fda4af' },
  'opened by': { label: 'Opened By', color: '#fde047' },
  'operated by': { label: 'Operated By', color: '#c084fc' },
  'operates at': { label: 'Operates At', color: '#fda4af' },
  'operates in': { label: 'Operates In', color: '#fda4af' },
  'ordered execution for': { label: 'Ordered Execution For', color: '#fda4af' },
  'originated from': { label: 'Originated From', color: '#c8a876' },
  'originates from': { label: 'Originates From', color: '#a855f7' },
  'overcomes': { label: 'Overcomes', color: '#a855f7' },
  'pacifiable by': { label: 'Pacifiable By', color: '#fb7185' },
  'parallel to': { label: 'Parallel To', color: '#34d399' },
  'parasitized by': { label: 'Parasitized By', color: '#a78bfa' },
  'parasitizes': { label: 'Parasitizes', color: '#38bdf8' },
  'parent race of': { label: 'Parent Race Of', color: '#34d399' },
  'partially redirected by': { label: 'Partially Redirected By', color: '#34d399' },
  'patrols': { label: 'Patrols', color: '#38bdf8' },
  'performed by': { label: 'Performed By', color: '#c084fc' },
  'possessed Potent Blood': { label: 'Possessed Potent Blood', color: '#c084fc' },
  'possessed by': { label: 'Possessed By', color: '#fda4af' },
  'potentially home to': { label: 'Potentially Home To', color: '#a78bfa' },
  'powered by': { label: 'Powered By', color: '#fb923c' },
  'practiced at': { label: 'Practiced At', color: '#c8a876' },
  'practiced by': { label: 'Practiced By', color: '#e879f9' },
  'practiced in': { label: 'Practiced In', color: '#c8a876' },
  'primary in': { label: 'Primary In', color: '#bef264' },
  'produced in': { label: 'Produced In', color: '#c084fc' },
  'progression of': { label: 'Progression Of', color: '#e879f9' },
  'protagonist of': { label: 'Protagonist Of', color: '#a78bfa' },
  'protect alongside': { label: 'Protect Alongside', color: '#bef264' },
  'protect seal of': { label: 'Protect Seal Of', color: '#fbbf24' },
  'racial half of': { label: 'Racial Half Of', color: '#f472b6' },
  'raised': { label: 'Raised', color: '#fde047' },
  'raised by': { label: 'Raised By', color: '#c4b5fd' },
  'read by': { label: 'Read By', color: '#c4b5fd' },
  'refused by': { label: 'Refused By', color: '#c084fc' },
  'related to': { label: 'Related To', color: '#c8a876' },
  'relates to': { label: 'Relates To', color: '#38bdf8' },
  'repelled by': { label: 'Repelled By', color: '#fda4af' },
  'required for': { label: 'Required For', color: '#facc15' },
  'resented': { label: 'Resented', color: '#e879f9' },
  'resides in': { label: 'Resides In', color: '#facc15' },
  'resulted in': { label: 'Resulted In', color: '#fb7185' },
  'results of': { label: 'Results Of', color: '#a855f7' },
  'revealed at': { label: 'Revealed At', color: '#fbbf24' },
  'rivals with': { label: 'Rivals With', color: '#fbbf24' },
  'rules from': { label: 'Rules From', color: '#a78bfa' },
  'sealed by': { label: 'Sealed By', color: '#a855f7' },
  'sees through': { label: 'Sees Through', color: '#818cf8' },
  'separates': { label: 'Separates', color: '#2dd4bf' },
  'sold in': { label: 'Sold In', color: '#a855f7' },
  'sole survivor is': { label: 'Sole Survivor Is', color: '#fbbf24' },
  'soothable by': { label: 'Soothable By', color: '#2dd4bf' },
  'source of': { label: 'Source Of', color: '#fda4af' },
  'starting rank at': { label: 'Starting Rank At', color: '#7f8fa3' },
  'studied at': { label: 'Studied At', color: '#a78bfa' },
  'studied by': { label: 'Studied By', color: '#bef264' },
  'superior to': { label: 'Superior To', color: '#4ade80' },
  'suppressed by': { label: 'Suppressed By', color: '#c4b5fd' },
  'takes place at': { label: 'Takes Place At', color: '#4ade80' },
  'threatens': { label: 'Threatens', color: '#facc15' },
  'took place in': { label: 'Took Place In', color: '#fb7185' },
  'trains': { label: 'Trains', color: '#fbbf24' },
  'trains as': { label: 'Trains As', color: '#a855f7' },
  'trains in': { label: 'Trains In', color: '#fda4af' },
  'transcend': { label: 'Transcend', color: '#2dd4bf' },
  'transforms': { label: 'Transforms', color: '#c084fc' },
  'travels through': { label: 'Travels Through', color: '#5eead4' },
  'travels to': { label: 'Travels To', color: '#facc15' },
  'triggered by': { label: 'Triggered By', color: '#4ade80' },
  'unique to': { label: 'Unique To', color: '#f87171' },
  'uniquely possesses': { label: 'Uniquely Possesses', color: '#fde047' },
  'use corrupted': { label: 'Use Corrupted', color: '#7f8fa3' },
  'use holy': { label: 'Use Holy', color: '#a855f7' },
  'use raw': { label: 'Use Raw', color: '#fb7185' },
  'used by': { label: 'Used By', color: '#fda4af' },
  'used by angels': { label: 'Used By Angels', color: '#facc15' },
  'used by demons': { label: 'Used By Demons', color: '#fde047' },
  'uses as transport': { label: 'Uses As Transport', color: '#c4b5fd' },
  'valued by': { label: 'Valued By', color: '#facc15' },
  'verifies': { label: 'Verifies', color: '#818cf8' },
  'vulnerable to': { label: 'Vulnerable To', color: '#c084fc' },
  'was': { label: 'Was', color: '#38bdf8' },
  'wider in': { label: 'Wider In', color: '#f87171' },
  'wielded by': { label: 'Wielded By', color: '#a855f7' },
  'witnessed by': { label: 'Witnessed By', color: '#818cf8' },
  'worn by': { label: 'Worn By', color: '#7f8fa3' },
  'would have triggered': { label: 'Would Have Triggered', color: '#f472b6' },
};

export const FALLBACK_STORY = { label: 'Related to', color: '#7f8fa3' };

export function storyLinkType(type: string): StoryLinkType {
  return STORY_LINK_TYPES[type] ?? { label: type, color: FALLBACK_STORY.color };
}
